export const ADD_OWNER = "ADD_OWNER";
export const ADD_ITEMS = "ADD_ITEMS"
export const CHANGE_ADDRESS = 'CHANGE_ADDRESS'
export const CHANGE_PHONE = 'CHANGE_PHONE'
export const DELETE_ITEMS = 'DELETE_ITEMS'
export const CHANGE_SEARCH = 'CHANGE_SEARCH'
export const CHANGE_SEARCH_GLOBAL = 'CHANGE_SEARCH_GLOBAL'

