export const ADD_OWNER = "ADD_OWNER";
export const ADD_ITEMS = "ADD_ITEMS"
export const CHANGE_ADDRESS = 'CHANGE_ADDRESS'
export const CHANGE_PHONE = 'CHANGE_PHONE'
export const DELETE_ITEMS = 'DELETE_ITEMS'
export const CHANGE_SEARCH = 'CHANGE_SEARCH'
export const CHANGE_SEARCH_GLOBAL = 'CHANGE_SEARCH_GLOBAL'
export const SEARCH_COLLECTION = 'SEARCH_COLLECTION'
export const LOAD_MORE = 'LOAD_MORE'
export const CATALOG_TITLE = 'CATALOG_TITLE'
export const SELECT_ITEM = 'SELECT_ITEM'
export const SELECT_ALL = 'SELECT_ALL'
export const GET_HITS = 'GET_HITS'

export const CATALOG_REQUEST = 'CATALOG_REQUEST'
export const CATALOG_SUCCESS = 'CATALOG_SUCCESS'
export const CATEGORY_REQUEST = 'CATEGORY_REQUEST'
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS'
export const TOP_REQUEST = 'TOP_REQUEST'
export const TOP_SUCCESS = 'TOP_SUCCESS'
export const TOP_FAILURE = 'TOP_FAILURE'
export const CATALOG_CLEAR = 'CATALOG_CLEAR'
export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const CATALOG_CHANGE_EXTRA = 'CATALOG_CHANGE_EXTRA'
export const SEARCH_CHANGE_EXTRA = 'SEARCH_CHANGE_EXTRA'
export const SEARCH_CLEAR = 'SEARCH_CLEAR'

export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'

// export const SELECT_SIZE = 'SELECT_SIZE'
// export const INCREMENT_SIZE = 'INCREMENT_SIZE'
// export const DECREMENT_SIZE = 'DECREMENT_SIZE'




